# Generated by Django 5.0.7 on 2024-08-13 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppBusConecta", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historial",
            name="tiempo",
        ),
    ]
