# Generated by Django 5.0.7 on 2024-08-15 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppBusConecta", "0003_historial_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historial",
            name="usuario",
        ),
    ]
